/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import CustomTableModel.CustomTableAccount;
import DAO.Implement.AccountDAO;
import Model.Account;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mrloc
 */
public class AccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountPanel
     */
    int listIndex = -1;
    ArrayList<Account> listTeacher = new ArrayList<>(); 
    ArrayList<Account> listStudent = new ArrayList<>(); 
    AccountDAO dao = new AccountDAO();           

    public AccountPanel() {
        initComponents();
        jTableTeacher.getTableHeader().setFont(new Font("Tomaho", Font.BOLD, 12));
        jTableStudent.getTableHeader().setFont(new Font("Tomaho", Font.BOLD, 12));
        loadData();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelTableMain = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTeacher = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonAddAccount = new javax.swing.JButton();
        jButtonChangeStatus = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(4, 178, 217));

        jLabelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))); // NOI18N
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBackMousePressed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279)
                .addComponent(jLabelTitle)
                .addGap(0, 364, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBack, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, -1));

        jPanelTableMain.setBackground(new java.awt.Color(4, 135, 217));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableTeacher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTeacher.setEnabled(false);
        jTableTeacher.setFocusable(false);
        jTableTeacher.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableTeacher.setOpaque(false);
        jTableTeacher.setRowHeight(22);
        jTableTeacher.setShowVerticalLines(false);
        jTableTeacher.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableTeacher);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tài khoản quản trị viên");

        jTableStudent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableStudent.setFocusable(false);
        jTableStudent.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableStudent.setOpaque(false);
        jTableStudent.setRowHeight(22);
        jTableStudent.setShowVerticalLines(false);
        jTableStudent.getTableHeader().setReorderingAllowed(false);
        jTableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableStudentMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableStudent);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tài khoản sinh viên");

        jButtonAddAccount.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddAccount.setForeground(new java.awt.Color(4, 135, 217));
        jButtonAddAccount.setText("THÊM TÀI KHOẢN");
        jButtonAddAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAccountActionPerformed(evt);
            }
        });

        jButtonChangeStatus.setBackground(new java.awt.Color(255, 255, 255));
        jButtonChangeStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonChangeStatus.setForeground(new java.awt.Color(4, 135, 217));
        jButtonChangeStatus.setText("ĐỔI TRẠNG THÁI");
        jButtonChangeStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonChangeStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTableMainLayout = new javax.swing.GroupLayout(jPanelTableMain);
        jPanelTableMain.setLayout(jPanelTableMainLayout);
        jPanelTableMainLayout.setHorizontalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTableMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanelTableMainLayout.setVerticalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelTableMainLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(27, 27, 27)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
            .addGroup(jPanelTableMainLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButtonAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanelTableMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1130, 520));

        add(jPanelMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void loadData() {
        listTeacher = (ArrayList<Account>) dao.findByRoles(true);   
        listStudent = (ArrayList<Account>) dao.findByRoles(false); 
        jTableTeacher.setModel(new CustomTableAccount(listTeacher));    
        jTableStudent.setModel(new CustomTableAccount(listStudent));
    }

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        // TODO add your handling code here:
        jLabelBack.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon_hover.png"))));
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        // TODO add your handling code here:
        jLabelBack.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))));
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jLabelBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMousePressed
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new MainAdminPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelBackMousePressed

    private void jButtonAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAccountActionPerformed
        // Mở một cái form thêm tài khoản lên
            AddAccountForm f = new AddAccountForm(null, true,this);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
    }//GEN-LAST:event_jButtonAddAccountActionPerformed

    private void jButtonChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeStatusActionPerformed
        // TODO add your handling code here:
        try {
            if (listIndex == -1) {      //Nếu chưa có dòng nào được chọn => listIndex = -1
                throw new Exception("Hãy chọn dòng cần sửa");
            } else {
                //nếu đã có dòng được chọn thì nó chính là phần tử thứ listIndex ở trong danh sách được lấy ở trên
                if (dao.changeStatus(listStudent.get(listIndex).getAccount_ID())) { //Nếu đổi trạng thái thành công
                    loadData();                         //Load lại dữ liệu
                    listIndex = -1;                     //Gán vị trí được chọn về -1 cho lần sửa sau
                } else {    //Ngược lại quăng lỗi
                    throw new Exception("Cập nhật không thành công");
                }
            }
        } catch (Exception e) { //Nếu có lỗi thông báo
            JOptionPane.showMessageDialog(jPanelMain, e.getMessage());
        }
    }//GEN-LAST:event_jButtonChangeStatusActionPerformed

    private void jTableStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStudentMousePressed
        // Hàm mouse pressed để gán giá trị cho listIndex khi click vào bảng. Phục vụ cho việc đổi trạng thái
        listIndex = jTableStudent.getSelectedRow();
    }//GEN-LAST:event_jTableStudentMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAccount;
    private javax.swing.JButton jButtonChangeStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTableMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTable jTableTeacher;
    // End of variables declaration//GEN-END:variables
}
