/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.Implement.ChapterDAO;
import DAO.Implement.LessonDAO;
import Model.Chapter;
import Model.Lesson;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mrloc
 */
public class AddAndEditLessonFom extends javax.swing.JDialog {

    /**
     * Creates new form AddLessonFom
     */
    int positionX, positionY;       //Cái này là di chuyển form. Đừng quan tâm
    SubjectPanel panelparent;       //Cái này là panel cha. Dùng để load lại data
    Lesson edit;                    //Đây là cái sẽ chưa cái Lesson cần edit
    LessonDAO lessonDAO = new LessonDAO();
    ArrayList<Chapter> listChapter = (ArrayList<Chapter>) new ChapterDAO().getAllChapter();
    //Danh sách chứa các chapter load lên combobox
    //Đừng quan tâm constructor này. Nó là mặc định đéo dùng đâu
    public AddAndEditLessonFom(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    //Cái constructor này dùng cho việc thêm. Cái javax.swing.JPanel panel chính là cái panel cha
    public AddAndEditLessonFom(java.awt.Frame parent, boolean modal, javax.swing.JPanel panel) {
        super(parent, modal);
        initComponents();
        panelparent = (SubjectPanel) panel;    
        jButtonEdit.setVisible(false);         
        jLabelTitle1.setVisible(false);
        try {                                   
            jComboBoxChapter.revalidate();    
            for (Chapter item : listChapter) {
                jComboBoxChapter.addItem(item.toString());
            }
        } catch (ArrayIndexOutOfBoundsException e) {
        }
    }
    
    //Constructor dùng để sửa đây nhé. Cái Lesson ls chính là cái lesson cần sửa
    public AddAndEditLessonFom(java.awt.Frame parent, boolean modal, Lesson ls) {
        super(parent, modal);
        initComponents();
        edit = ls;      //gán cái edit chính là cái ls
        jTextLesson.setText(ls.getLesson()+ "");      
        jTextLessonName.setText(ls.getLesson_Name());
        jButtonAdd.setVisible(false);   //ẩn nút thêm và title thêm
        jLabelTitle.setVisible(false);
        jComboBoxChapter.addItem(new ChapterDAO().findByID(ls.getChapter_ID()).toString()); //load lại dữ liệu lên combobox.
        jTextLesson.setEditable(false);     //Tuy nhiên ko cho sửa
        jComboBoxChapter.disable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jPanelMove = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelLesson = new javax.swing.JLabel();
        jTextLesson = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelChapter = new javax.swing.JLabel();
        jLabelLessonName = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextLessonName = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jLabelTitle1 = new javax.swing.JLabel();
        jComboBoxChapter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTop.setBackground(new java.awt.Color(0, 51, 153));
        jPanelTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMove.setBackground(new java.awt.Color(0, 51, 153));
        jPanelMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelMoveMouseDragged(evt);
            }
        });
        jPanelMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelMoveMousePressed(evt);
            }
        });

        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMoveLayout = new javax.swing.GroupLayout(jPanelMove);
        jPanelMove.setLayout(jPanelMoveLayout);
        jPanelMoveLayout.setHorizontalGroup(
            jPanelMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMoveLayout.createSequentialGroup()
                .addGap(0, 386, Short.MAX_VALUE)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMoveLayout.setVerticalGroup(
            jPanelMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoveLayout.createSequentialGroup()
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanelTop.add(jPanelMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        jPanel1.add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 436, 42));

        jLabelTitle.setFont(new java.awt.Font("Minion Pro", 1, 36)); // NOI18N
        jLabelTitle.setText("Thêm bài");
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabelLesson.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLesson.setText("Bài số :");
        jPanel1.add(jLabelLesson, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 139, -1, -1));

        jTextLesson.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextLesson.setBorder(null);
        jPanel1.add(jTextLesson, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 139, 250, -1));

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAdd.setText("Thêm mới");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 162, 250, 10));

        jLabelChapter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChapter.setText("Chương :");
        jPanel1.add(jLabelChapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabelLessonName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLessonName.setText("Tên bài :");
        jPanel1.add(jLabelLessonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 199, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 222, 250, 10));

        jTextLessonName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextLessonName.setBorder(null);
        jPanel1.add(jTextLessonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 199, 250, -1));

        jButtonEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEdit.setText("Cập nhật");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabelTitle1.setFont(new java.awt.Font("Minion Pro", 1, 36)); // NOI18N
        jLabelTitle1.setText("Sửa bài");
        jPanel1.add(jLabelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jPanel1.add(jComboBoxChapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        // TODO add your handling code here:
        jLabelExit.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/close_hover.png"))));
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        // TODO add your handling code here:
        jLabelExit.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jPanelMoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMoveMouseDragged

        // TODO add your handling code here:
        this.setLocation(this.getX() + evt.getX() - positionX, this.getY() + evt.getY() - positionY);
    }//GEN-LAST:event_jPanelMoveMouseDragged

    private void jPanelMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMoveMousePressed
        // TODO add your handling code here:
        positionX = evt.getX();
        positionY = evt.getY();
    }//GEN-LAST:event_jPanelMoveMousePressed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        do {
            try {
                int lesson;
                int indexChapter = jComboBoxChapter.getSelectedIndex();     
                try {
                    lesson = Integer.parseInt(jTextLesson.getText());  
                    if (lesson < 1) {              
                        throw new NumberFormatException();
                    }
                } catch (NumberFormatException ex) {
                    throw new Exception("Sai định dạng bài");
                }
                if (lessonDAO.findByLessonAndChapterID(lesson,listChapter.get(indexChapter).getChapter_ID()) != null) {
                    throw new Exception("Bài " + lesson + " chương " + listChapter.get(indexChapter).getChapter() + " đã tồn tại");
                }
                String lessonName = jTextLessonName.getText();
                if (lessonName.trim().equals("")) {
                    throw new Exception("Tên bài không được để trống");
                }
                Lesson inserted = lessonDAO.add(new Lesson(0, lesson, lessonName, listChapter.get(indexChapter).getChapter_ID()));
                panelparent.loadData(); 
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn tiếp tục thêm không ?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
                    this.dispose();
                    break;
                } else {
                    clear();
                    break;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
                return;
            }
        } while (true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    //Hàm xóa dữ liệu
    private void clear(){
        jTextLesson.setText("");
        jTextLessonName.setText("");
        jComboBoxChapter.setSelectedIndex(0);
        jTextLesson.requestFocus();
    }
    
    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        try {
            String lessonName = jTextLessonName.getText();
            if (lessonName.trim().equals("")) {
                throw new Exception("Tên chương không được để trống");
            }
            Boolean isUpdated = lessonDAO.updateLessonNameByID(new Lesson(edit.getLesson_ID(),edit.getLesson(),lessonName,edit.getChapter_ID()));
            if(isUpdated){
                this.dispose();
            }else{
                throw new Exception("Lỗi ! Cập nhật không thành công");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            return;
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAndEditLessonFom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAndEditLessonFom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAndEditLessonFom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAndEditLessonFom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddAndEditLessonFom dialog = new AddAndEditLessonFom(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox<String> jComboBoxChapter;
    private javax.swing.JLabel jLabelChapter;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelLesson;
    private javax.swing.JLabel jLabelLessonName;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMove;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextLesson;
    private javax.swing.JTextField jTextLessonName;
    // End of variables declaration//GEN-END:variables
}
