/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author mrloc
 */
public class MainAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainAdminPanel
     */
    public MainAdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelComponent = new javax.swing.JPanel();
        jPanelSubject = new javax.swing.JPanel();
        jLabelSubject = new javax.swing.JLabel();
        jPanelTest = new javax.swing.JPanel();
        jLabelTest = new javax.swing.JLabel();
        jPanelColclusion = new javax.swing.JPanel();
        jLabelConclution = new javax.swing.JLabel();
        jPanelAccount = new javax.swing.JPanel();
        jLabelAccount = new javax.swing.JLabel();
        jPanelQuestion = new javax.swing.JPanel();
        jLabelQuestion = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitle.setBackground(new java.awt.Color(4, 178, 217));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HỆ THỐNG QUẢN LÝ THI TRẮC NGHIỆM HAUI");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTitleLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(jPanelTitleLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 230));

        jPanelComponent.setBackground(new java.awt.Color(4, 135, 217));
        jPanelComponent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSubject.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSubject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/subjectadmin.png"))); // NOI18N
        jLabelSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSubjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSubjectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSubjectMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSubjectLayout = new javax.swing.GroupLayout(jPanelSubject);
        jPanelSubject.setLayout(jPanelSubjectLayout);
        jPanelSubjectLayout.setHorizontalGroup(
            jPanelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanelSubjectLayout.setVerticalGroup(
            jPanelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        jPanelComponent.add(jPanelSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, 290));

        jPanelTest.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/testadmin.png"))); // NOI18N
        jLabelTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTestMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelTestMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTestLayout = new javax.swing.GroupLayout(jPanelTest);
        jPanelTest.setLayout(jPanelTestLayout);
        jPanelTestLayout.setHorizontalGroup(
            jPanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTest, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanelTestLayout.setVerticalGroup(
            jPanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTest, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        jPanelComponent.add(jPanelTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, 290));

        jPanelColclusion.setBackground(new java.awt.Color(255, 255, 255));

        jLabelConclution.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConclution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sumupadmin.png"))); // NOI18N
        jLabelConclution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConclution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelConclutionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelConclutionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelConclutionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelColclusionLayout = new javax.swing.GroupLayout(jPanelColclusion);
        jPanelColclusion.setLayout(jPanelColclusionLayout);
        jPanelColclusionLayout.setHorizontalGroup(
            jPanelColclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelConclution, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanelColclusionLayout.setVerticalGroup(
            jPanelColclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelConclution, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        jPanelComponent.add(jPanelColclusion, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, -1, 290));

        jPanelAccount.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAccount.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/accountadmin.png"))); // NOI18N
        jLabelAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAccountMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAccountMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAccountLayout = new javax.swing.GroupLayout(jPanelAccount);
        jPanelAccount.setLayout(jPanelAccountLayout);
        jPanelAccountLayout.setHorizontalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanelAccountLayout.setVerticalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        jPanelComponent.add(jPanelAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 290));

        jPanelQuestion.setBackground(new java.awt.Color(255, 255, 255));

        jLabelQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/questionadmin.png"))); // NOI18N
        jLabelQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelQuestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelQuestionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelQuestionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuestionLayout = new javax.swing.GroupLayout(jPanelQuestion);
        jPanelQuestion.setLayout(jPanelQuestionLayout);
        jPanelQuestionLayout.setHorizontalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanelQuestionLayout.setVerticalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        jPanelComponent.add(jPanelQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, 290));

        jPanelMain.add(jPanelComponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1130, 390));

        add(jPanelMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccountMouseEntered
        jPanelAccount.setBackground(new Color(243, 209, 220));
    }//GEN-LAST:event_jLabelAccountMouseEntered

    private void jLabelAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccountMouseExited
        jPanelAccount.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelAccountMouseExited

    private void jLabelSubjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSubjectMouseEntered
        jPanelSubject.setBackground(new Color(243, 209, 220));
    }//GEN-LAST:event_jLabelSubjectMouseEntered

    private void jLabelSubjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSubjectMouseExited
        jPanelSubject.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelSubjectMouseExited

    private void jLabelTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTestMouseEntered
        jPanelTest.setBackground(new Color(243, 209, 220));
    }//GEN-LAST:event_jLabelTestMouseEntered

    private void jLabelTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTestMouseExited
        jPanelTest.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelTestMouseExited

    private void jLabelQuestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuestionMouseEntered
        jPanelQuestion.setBackground(new Color(243, 209, 220));
    }//GEN-LAST:event_jLabelQuestionMouseEntered

    private void jLabelQuestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuestionMouseExited
        jPanelQuestion.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelQuestionMouseExited

    private void jLabelConclutionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConclutionMouseEntered
        jPanelColclusion.setBackground(new Color(243, 209, 220));
    }//GEN-LAST:event_jLabelConclutionMouseEntered

    private void jLabelConclutionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConclutionMouseExited
        jPanelColclusion.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelConclutionMouseExited

    private void jLabelAccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccountMousePressed
        // TODO add your handling code here:
        JPanel parent = (JPanel) this.getParent();
        this.hide();
        parent.add(new AccountPanel());
        parent.revalidate();
    }//GEN-LAST:event_jLabelAccountMousePressed

    private void jLabelSubjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSubjectMousePressed
        // TODO add your handling code here:
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new SubjectPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelSubjectMousePressed

    private void jLabelTestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTestMousePressed
        // TODO add your handling code here:
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new TestPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelTestMousePressed

    private void jLabelQuestionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuestionMousePressed
        // TODO add your handling code here:
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new QuestionPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelQuestionMousePressed

    private void jLabelConclutionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConclutionMousePressed
        // TODO add your handling code here:
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new StatisticPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelConclutionMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAccount;
    private javax.swing.JLabel jLabelConclution;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelTest;
    private javax.swing.JPanel jPanelAccount;
    private javax.swing.JPanel jPanelColclusion;
    private javax.swing.JPanel jPanelComponent;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelQuestion;
    private javax.swing.JPanel jPanelSubject;
    private javax.swing.JPanel jPanelTest;
    private javax.swing.JPanel jPanelTitle;
    // End of variables declaration//GEN-END:variables
}
