/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import CustomTableModel.CustomTableQuestion;
import DAO.Implement.ChapterDAO;
import DAO.Implement.LessonDAO;
import DAO.Implement.LevelDAO;
import DAO.Implement.QuestionDAO;
import Model.Chapter;
import Model.Lesson;
import Model.Level;
import Model.Question;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mrloc
 */
public class QuestionPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestionPanel
     */
    ArrayList<Chapter> listChapter = (ArrayList<Chapter>) new ChapterDAO().getAllChapter();
    ArrayList<Lesson> listLesson;
    ArrayList<Level> listLevel = (ArrayList<Level>) new LevelDAO().getAllLevel();
    ArrayList<Question> listQuestion = new ArrayList<>();
    QuestionDAO questionDAO = new QuestionDAO();
    int indexQuestion = -1;
    private Level lv;
    private Chapter c;
    private Lesson l;

    public QuestionPanel() {
        initComponents();
        loadChapter();
        loadLevel();
        loadData();
    }

    public void loadData() {
        loadAllQuestion();
    }

    //cái này là load toàn bộ câu hỏi
    private void loadAllQuestion() {
        listQuestion = (ArrayList<Question>) questionDAO.getAllQuestion();
        jTableQuestion.setModel(new CustomTableQuestion(listQuestion));
    }

    //cái này load câu hỏi theo chương
    private void loadQuestionByChapter(int chapter_ID) {
        listQuestion = (ArrayList<Question>) questionDAO.getQuestionsByChapterID(chapter_ID);
        jTableQuestion.setModel(new CustomTableQuestion(listQuestion));
    }

    //cái này là load theo chương và độ khó
    private void loadQuestionByChapterAndLevel(int chapter_ID, int level_ID) {
        listQuestion = (ArrayList<Question>) questionDAO.getQuestionsByChapterIDAndLevelID(chapter_ID, level_ID);
        jTableQuestion.setModel(new CustomTableQuestion(listQuestion));
    }

    //cái này là load theo độ khó
    private void loadQuestionByLevel(int level_ID) {
        listQuestion = (ArrayList<Question>) questionDAO.getQuestionByLevelID(level_ID);
        jTableQuestion.setModel(new CustomTableQuestion(listQuestion));
    }

    //cái này là load theo bài
    private void loadQuestionByLessonID(int lesson_ID) {
        listQuestion = (ArrayList<Question>) questionDAO.getQuestionByLessonID(lesson_ID);
        jTableQuestion.setModel(new CustomTableQuestion(listQuestion));
    }

    //cái này là load theo bài và độ khó
    private void loadQuestionByLessonAndLevel(int lessonID, int leveID) {
        listQuestion = (ArrayList<Question>) questionDAO.getQuestionByLessonIDAndLevelID(lessonID, leveID);
        jTableQuestion.setModel(new CustomTableQuestion(listQuestion));
    }

    private void loadChapter() {
        jComboBoxChapter.addItem("Tất cả");
        for (Chapter item : listChapter) {
            jComboBoxChapter.addItem(item.toString());
        }
    }

    private void loadLevel() {
        jComboBoxLevel.addItem("Tất cả");
        for (Level item : listLevel) {
            jComboBoxLevel.addItem(item.getLevel_Name());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelBack2 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelTableMain = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuestion = new javax.swing.JTable();
        jButtonAddQuestion = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelChapter = new javax.swing.JLabel();
        jLabelLesson = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jComboBoxChapter = new javax.swing.JComboBox<>();
        jComboBoxLesson = new javax.swing.JComboBox<>();
        jComboBoxLevel = new javax.swing.JComboBox<>();

        jPanelMain2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(4, 178, 217));

        jLabelBack2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))); // NOI18N
        jLabelBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBack2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBack2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBack2MousePressed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("QUẢN LÝ CÂU HỎI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279)
                .addComponent(jLabelTitle)
                .addGap(0, 413, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBack2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTableMain.setBackground(new java.awt.Color(4, 135, 217));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonFilter.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFilter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonFilter.setForeground(new java.awt.Color(4, 135, 217));
        jButtonFilter.setText("LỌC CÂU HỎI");
        jButtonFilter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTableQuestion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableQuestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableQuestion.setFocusable(false);
        jTableQuestion.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableQuestion.setOpaque(false);
        jTableQuestion.setRowHeight(22);
        jTableQuestion.setShowVerticalLines(false);
        jTableQuestion.getTableHeader().setReorderingAllowed(false);
        jTableQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQuestionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableQuestionMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableQuestion);

        jButtonAddQuestion.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddQuestion.setForeground(new java.awt.Color(4, 135, 217));
        jButtonAddQuestion.setText("THÊM CÂU HỎI");
        jButtonAddQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddQuestionActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(4, 135, 217));
        jButtonDelete.setText("XÓA CÂU HỎI");
        jButtonDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelChapter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChapter.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChapter.setText("Chương :");

        jLabelLesson.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLesson.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLesson.setText("Bài :");

        jLabelLevel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLevel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLevel.setText("Độ khó :");

        jComboBoxChapter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxChapterItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelTableMainLayout = new javax.swing.GroupLayout(jPanelTableMain);
        jPanelTableMain.setLayout(jPanelTableMainLayout);
        jPanelTableMainLayout.setHorizontalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTableMainLayout.createSequentialGroup()
                        .addComponent(jLabelChapter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLesson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanelTableMainLayout.setVerticalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChapter)
                    .addComponent(jLabelLesson)
                    .addComponent(jLabelLevel)
                    .addComponent(jComboBoxChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanelTableMainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButtonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMain2Layout = new javax.swing.GroupLayout(jPanelMain2);
        jPanelMain2.setLayout(jPanelMain2Layout);
        jPanelMain2Layout.setHorizontalGroup(
            jPanelMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelTableMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelMain2Layout.setVerticalGroup(
            jPanelMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMain2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelTableMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMain2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMain2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBack2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBack2MouseEntered
        // TODO add your handling code here:
        jLabelBack2.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon_hover.png"))));
    }//GEN-LAST:event_jLabelBack2MouseEntered

    private void jLabelBack2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBack2MouseExited
        // TODO add your handling code here:
        jLabelBack2.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))));
    }//GEN-LAST:event_jLabelBack2MouseExited

    private void jLabelBack2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBack2MousePressed
        // TODO add your handling code here:
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new MainAdminPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelBack2MousePressed

    private void jButtonAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddQuestionActionPerformed
        // khởi tạo form thêm. Truyền vào this chính là cái panel cha đề load lại data bên kia
        AddAndEditQuestionForm f = new AddAndEditQuestionForm(null, true, this);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButtonAddQuestionActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        try {
            if (indexQuestion == -1) {
                throw new Exception("Hãy chọn câu hỏi cần xóa");
            } else {
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá câu hỏi : " + listQuestion.get(indexQuestion).getQuestion() + " không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    //Lấy cái câu hỏi tại vị trí indexQuestion trong list và xóa theo ID
                    if (questionDAO.deleteQuestion(listQuestion.get(indexQuestion).getQuestion_ID())) {
                        JOptionPane.showMessageDialog(this, "Xóa thành công!");
                        loadData();
                        indexQuestion = -1;
                    } else {
                        throw new Exception("Lỗi! Xóa không thành công");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jComboBoxChapterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxChapterItemStateChanged
        // TODO add your handling code here:
        jComboBoxLesson.removeAllItems();
        jComboBoxLesson.addItem("Tất cả");
        if (!jComboBoxChapter.getSelectedItem().toString().equals("Tất cả")) {
            listLesson = (ArrayList<Lesson>) new LessonDAO().findByChapterID(listChapter.get(jComboBoxChapter.getSelectedIndex() - 1).getChapter_ID());
            for (Lesson item : listLesson) {
                jComboBoxLesson.addItem(item.getLesson() + " : " + item.getLesson_Name());
            }
        }
    }//GEN-LAST:event_jComboBoxChapterItemStateChanged

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        // TODO add your handling code here:
        String chap = jComboBoxChapter.getSelectedItem().toString();
        String less = jComboBoxLesson.getSelectedItem().toString();
        String diff = jComboBoxLevel.getSelectedItem().toString();
        if (chap.equals("Tất cả")) {
            if (diff.equals("Tất cả")) {
                loadAllQuestion();
            } else {
                loadQuestionByLevel(listLevel.get(jComboBoxLevel.getSelectedIndex() - 1).getLevel_ID());
            }
        } else {
            if (less.equals("Tất cả")) {
                if (diff.equals("Tất cả")) {
                    loadQuestionByChapter(listChapter.get(jComboBoxChapter.getSelectedIndex() - 1).getChapter_ID());
                } else {
                    loadQuestionByChapterAndLevel(listChapter.get(jComboBoxChapter.getSelectedIndex() - 1).getChapter_ID(), listLevel.get(jComboBoxLevel.getSelectedIndex() - 1).getLevel_ID());
                }
            } else {
                if (diff.equals("Tất cả")) {
                    loadQuestionByLessonID(listLesson.get(jComboBoxLesson.getSelectedIndex() - 1).getLesson_ID());
                } else {
                    loadQuestionByLessonAndLevel(listLesson.get(jComboBoxLesson.getSelectedIndex() - 1).getLesson_ID(), listLevel.get(jComboBoxLevel.getSelectedIndex() - 1).getLevel_ID());
                }
            }
        }
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jTableQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuestionMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {     // to detect doble click events
            AddAndEditQuestionForm f = new AddAndEditQuestionForm(null, true, listQuestion.get(indexQuestion));
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            loadData();
            indexQuestion = -1;
        }
    }//GEN-LAST:event_jTableQuestionMouseClicked

    private void jTableQuestionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuestionMousePressed
        // TODO add your handling code here:
        indexQuestion = jTableQuestion.getSelectedRow();
    }//GEN-LAST:event_jTableQuestionMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddQuestion;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JComboBox<String> jComboBoxChapter;
    private javax.swing.JComboBox<String> jComboBoxLesson;
    private javax.swing.JComboBox<String> jComboBoxLevel;
    private javax.swing.JLabel jLabelBack2;
    private javax.swing.JLabel jLabelChapter;
    private javax.swing.JLabel jLabelLesson;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMain2;
    private javax.swing.JPanel jPanelTableMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableQuestion;
    // End of variables declaration//GEN-END:variables

}
