/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import CustomTableModel.CustomTableResult;
import DAO.Implement.ResultDAO;
import Model.Result;
import javax.swing.JPanel;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mrloc
 */
public class StatisticPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticPanel
     */
    ResultDAO resultDAO = new ResultDAO();
    ArrayList<Result> listResult = new ArrayList<>();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public StatisticPanel() {
        initComponents();
        loadData();
    }

    private void loadData() {
        Date date;
        try{
            date = Date.valueOf(dateFormat.format(jDateChooser1.getDate()));
        }catch(NullPointerException e){
            date = null;
        }
        jTextAccountName.setText("");
        listResult = (ArrayList<Result>) resultDAO.getListResultByDateAndUserName(date, "");
        jTableStatistic.setModel(new CustomTableResult(listResult));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelTableMain = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStatistic = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabelTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextAccountName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonDeleteResult = new javax.swing.JButton();

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(4, 178, 217));

        jLabelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))); // NOI18N
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBackMousePressed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("THỐNG KÊ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(411, 411, 411)
                .addComponent(jLabelTitle)
                .addGap(0, 425, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBack, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, -1));

        jPanelTableMain.setBackground(new java.awt.Color(4, 135, 217));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableStatistic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableStatistic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableStatistic.setFocusable(false);
        jTableStatistic.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableStatistic.setOpaque(false);
        jTableStatistic.setRowHeight(22);
        jTableStatistic.setShowVerticalLines(false);
        jTableStatistic.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableStatistic);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jLabelTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTime.setText("Chọn ngày :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tài khoản :");

        jTextAccountName.setBackground(new java.awt.Color(4, 135, 217));
        jTextAccountName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextAccountName.setForeground(new java.awt.Color(255, 255, 255));
        jTextAccountName.setBorder(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/searchicon.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jButtonDeleteResult.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeleteResult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDeleteResult.setForeground(new java.awt.Color(4, 135, 217));
        jButtonDeleteResult.setText("XÓA KẾT QUẢ");
        jButtonDeleteResult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeleteResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTableMainLayout = new javax.swing.GroupLayout(jPanelTableMain);
        jPanelTableMain.setLayout(jPanelTableMainLayout);
        jPanelTableMainLayout.setHorizontalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addComponent(jLabelTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jTextAccountName, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonDeleteResult, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanelTableMainLayout.setVerticalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableMainLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jTextAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelTableMainLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButtonDeleteResult, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanelTableMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1130, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        // TODO add your handling code here:
        jLabelBack.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon_hover.png"))));
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        // TODO add your handling code here:
        jLabelBack.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))));
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jLabelBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMousePressed
        // Đây là hàm quay về. Cái mũi tên ý. Nó lấy cái panel cha rồi removeall đi và thêm panel main vào
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new MainAdminPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelBackMousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        Date date;
        try{
            date = Date.valueOf(dateFormat.format(jDateChooser1.getDate()));
        }catch(NullPointerException e){
            date = null;
        }
        if (jTextAccountName.getText().trim().equals("")) {
            listResult = (ArrayList<Result>) resultDAO.getListResultByDateAndUserName(date, "");
        } else {
            listResult = (ArrayList<Result>) resultDAO.getListResultByDateAndUserName(date, jTextAccountName.getText().trim());
        }
        jTableStatistic.setModel(new CustomTableResult(listResult));
    }//GEN-LAST:event_jLabel2MousePressed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        Date date;
        try{
            date = Date.valueOf(dateFormat.format(jDateChooser1.getDate()));
        }catch(NullPointerException e){
            date = null;
        }
        if (jTextAccountName.getText().trim().equals("")) {
            listResult = (ArrayList<Result>) resultDAO.getListResultByDateAndUserName(date, "");
        } else {
            listResult = (ArrayList<Result>) resultDAO.getListResultByDateAndUserName(date, jTextAccountName.getText().trim());
        }
        jTableStatistic.setModel(new CustomTableResult(listResult));
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jButtonDeleteResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteResultActionPerformed
        // TODO add your handling code here:
        int index = jTableStatistic.getSelectedRow();
        try {
            if (index == -1) {
                throw new Exception("Hãy chọn kết quả cần xóa!");
            } else {
                if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa kết quả này không ?",
                        "Cảnh Báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if (resultDAO.deleteResultByID(listResult.get(index).getResult_ID())) {
                        JOptionPane.showMessageDialog(this, "Xóa thành công!");
                        loadData();
                    } else {
                        throw new Exception("Có lỗi gì đó! Xóa không thành công!");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteResultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteResult;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTableMain;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableStatistic;
    private javax.swing.JTextField jTextAccountName;
    // End of variables declaration//GEN-END:variables
}
