/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import CustomTableModel.CustomTableChapter;
import CustomTableModel.CustomTableLesson;
import DAO.Implement.ChapterDAO;
import DAO.Implement.LessonDAO;
import Model.Chapter;
import Model.Lesson;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mrloc
 */
public class SubjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubjectPanel
     */
    int indexComboBox = 0;
    int indexChapter = -1;
    int indexLesson = -1;

    ArrayList<Chapter> listChapter = new ArrayList<>();
    ArrayList<Lesson> listLesson = new ArrayList<>();
    LessonDAO lessonDAO = new LessonDAO();
    ChapterDAO chapterDAO = new ChapterDAO();

    public SubjectPanel() {
        initComponents();
        jTableChapter.getTableHeader().setFont(new Font("Tomaho", Font.BOLD, 12));
        jTableLesson.getTableHeader().setFont(new Font("Tomaho", Font.BOLD, 12));
        loadData();     //load dữ liệu ra combobox
    }

    public void loadData() {
        listChapter = (ArrayList<Chapter>) chapterDAO.getAllChapter();
        jTableChapter.setModel(new CustomTableChapter(listChapter));
        if (jComboBoxChapter.getItemCount() != 0) {
            try {
                jComboBoxChapter.removeAllItems();
            } catch (ArrayIndexOutOfBoundsException e) {
            }
        }
        try {
            jComboBoxChapter.revalidate();
            for (Chapter item : listChapter) {
                jComboBoxChapter.addItem(item.toString());
            }
            jComboBoxChapter.setSelectedIndex(indexComboBox);
            listLesson = (ArrayList<Lesson>) lessonDAO.findByChapterID(listChapter.get(indexComboBox).getChapter_ID());
            jTableLesson.setModel(new CustomTableLesson(listLesson));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelTableMain = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableChapter = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLesson = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxChapter = new javax.swing.JComboBox<>();
        jButtonAddChapter = new javax.swing.JButton();
        jButtonDeleteChapter = new javax.swing.JButton();
        jButtonAddLesson = new javax.swing.JButton();
        jButtonDeleteLesson = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(4, 178, 217));

        jLabelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))); // NOI18N
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBackMousePressed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("QUẢN LÝ CHƯƠNG TRÌNH HỌC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(jLabelTitle)
                .addGap(0, 272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBack, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, -1));

        jPanelTableMain.setBackground(new java.awt.Color(4, 135, 217));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableChapter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableChapter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableChapter.setFocusable(false);
        jTableChapter.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableChapter.setOpaque(false);
        jTableChapter.setRowHeight(22);
        jTableChapter.setShowVerticalLines(false);
        jTableChapter.getTableHeader().setReorderingAllowed(false);
        jTableChapter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableChapterMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableChapterMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableChapter);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Danh sách chương");

        jTableLesson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableLesson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableLesson.setFocusable(false);
        jTableLesson.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableLesson.setOpaque(false);
        jTableLesson.setRowHeight(22);
        jTableLesson.setShowVerticalLines(false);
        jTableLesson.getTableHeader().setReorderingAllowed(false);
        jTableLesson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLessonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableLessonMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLesson);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Danh sách bài học");

        jComboBoxChapter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxChapterItemStateChanged(evt);
            }
        });

        jButtonAddChapter.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddChapter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddChapter.setForeground(new java.awt.Color(4, 135, 217));
        jButtonAddChapter.setText("THÊM CHƯƠNG");
        jButtonAddChapter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddChapter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddChapterActionPerformed(evt);
            }
        });

        jButtonDeleteChapter.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeleteChapter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDeleteChapter.setForeground(new java.awt.Color(4, 135, 217));
        jButtonDeleteChapter.setText("XÓA CHƯƠNG");
        jButtonDeleteChapter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeleteChapter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteChapterActionPerformed(evt);
            }
        });

        jButtonAddLesson.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddLesson.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddLesson.setForeground(new java.awt.Color(4, 135, 217));
        jButtonAddLesson.setText("THÊM BÀI");
        jButtonAddLesson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddLesson.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddLessonActionPerformed(evt);
            }
        });

        jButtonDeleteLesson.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeleteLesson.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDeleteLesson.setForeground(new java.awt.Color(4, 135, 217));
        jButtonDeleteLesson.setText("XÓA BÀI");
        jButtonDeleteLesson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeleteLesson.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTableMainLayout = new javax.swing.GroupLayout(jPanelTableMain);
        jPanelTableMain.setLayout(jPanelTableMainLayout);
        jPanelTableMainLayout.setHorizontalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTableMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTableMainLayout.createSequentialGroup()
                                .addComponent(jButtonAddChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jButtonDeleteChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2))
                    .addComponent(jComboBoxChapter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTableMainLayout.setVerticalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(jComboBoxChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelTableMainLayout.createSequentialGroup()
                                .addComponent(jButtonAddLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDeleteLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDeleteChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        jPanelMain.add(jPanelTableMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1130, 520));

        add(jPanelMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        // TODO add your handling code here:
        jLabelBack.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon_hover.png"))));
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        // TODO add your handling code here:
        jLabelBack.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))));
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jLabelBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMousePressed
        // TODO add your handling code here:
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new MainAdminPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelBackMousePressed

    private void jComboBoxChapterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxChapterItemStateChanged
        // load lại dữ liệu lên jtable lesson
        indexComboBox = jComboBoxChapter.getSelectedIndex() == -1 ? 0 : jComboBoxChapter.getSelectedIndex();
        listLesson = (ArrayList<Lesson>) lessonDAO.findByChapterID(listChapter.get(indexComboBox).getChapter_ID());
        jTableLesson.setModel(new CustomTableLesson(listLesson));
    }//GEN-LAST:event_jComboBoxChapterItemStateChanged

    private void jButtonAddChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddChapterActionPerformed
        // TODO add your handling code here:
        AddAndEditChapterForm f = new AddAndEditChapterForm(null, true, this);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButtonAddChapterActionPerformed

    private void jButtonDeleteChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteChapterActionPerformed
        try {
            int index = jTableChapter.getSelectedRow();
            try {
                if (JOptionPane.showConfirmDialog(jPanelMain, "Bạn có chắc chắn muốn xóa " + listChapter.get(index).toString()
                        + " không ? Việc này sẽ xóa tất cả bài và câu hỏi của chương này !",
                        "Cảnh Báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    //lấy cái chapter trong listChapter có index = dòng được chọn
                    Boolean isDeleted = chapterDAO.deleteChapterByID(listChapter.get(index).getChapter_ID());
                    if (isDeleted) {
                        try {
                            loadData();
                        } catch (Exception e) {
                        }
                    } else {
                        throw new Exception("Lỗi! Xóa không thành công");
                    }
                }
            } catch (ArrayIndexOutOfBoundsException ex) {
                throw new Exception("Hãy chọn chương cần xóa!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanelMain, e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteChapterActionPerformed

    private void jTableChapterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableChapterMousePressed
        // TODO add your handling code here:
        indexChapter = jTableChapter.getSelectedRow();
    }//GEN-LAST:event_jTableChapterMousePressed

    private void jTableChapterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableChapterMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {     // to detect doble click events
            AddAndEditChapterForm f = new AddAndEditChapterForm(null, true, listChapter.get(indexChapter));
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            indexChapter = -1;
            loadData();
        }
    }//GEN-LAST:event_jTableChapterMouseClicked

    private void jButtonAddLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddLessonActionPerformed
        // TODO add your handling code here:
        AddAndEditLessonFom f = new AddAndEditLessonFom(null, true, this);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButtonAddLessonActionPerformed

    private void jTableLessonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLessonMousePressed
        // TODO add your handling code here:
        indexLesson = jTableLesson.getSelectedRow();
    }//GEN-LAST:event_jTableLessonMousePressed

    private void jTableLessonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLessonMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {     // to detect doble click events
            AddAndEditLessonFom f = new AddAndEditLessonFom(null, true, listLesson.get(indexLesson));
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            indexChapter = -1;
            loadData();
        }
    }//GEN-LAST:event_jTableLessonMouseClicked

    private void jButtonDeleteLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteLessonActionPerformed
        try {
            int index = jTableLesson.getSelectedRow();
            try {
                if (JOptionPane.showConfirmDialog(jPanelMain, "Bạn có chắc chắn muốn xóa "
                        + listLesson.get(index).getLesson_Name() + " không ? Việc này sẽ xóa tất cả câu hỏi của bài này !",
                        "Cảnh Báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    //Lấy cái Lesson trong listLesson tại vị trí index và xóa
                    Boolean isDeleted = lessonDAO.deleteByID(listLesson.get(index).getLesson_ID());
                    if (isDeleted) {
                        loadData();
                        indexChapter = -1;
                    } else {
                        throw new Exception("Lỗi! Xóa không thành công");
                    }
                }
            } catch (ArrayIndexOutOfBoundsException ex) {
                throw new Exception("Hãy chọn bài cần xóa");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanelMain, e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteLessonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddChapter;
    private javax.swing.JButton jButtonAddLesson;
    private javax.swing.JButton jButtonDeleteChapter;
    private javax.swing.JButton jButtonDeleteLesson;
    private javax.swing.JComboBox<String> jComboBoxChapter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTableMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableChapter;
    private javax.swing.JTable jTableLesson;
    // End of variables declaration//GEN-END:variables
}
