/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import CustomTableModel.CustomTableTest;
import CustomTableModel.CustomTableTestQuestion;
import DAO.Implement.QuestionDAO;
import DAO.Implement.TestDAO;
import Model.Question;
import Model.Test;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mrloc
 */
public class TestPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    TestDAO testDAO = new TestDAO();
    QuestionDAO questionDAO = new QuestionDAO();
    ArrayList<Test> listTest = new ArrayList<>();
    ArrayList<Question> listQuestion = new ArrayList<>();

    public TestPanel() {
        initComponents();
        jTableTest.getTableHeader().setFont(new Font("Tomaho", Font.BOLD, 12));
        jTableQuestions.getTableHeader().setFont(new Font("Tomaho", Font.BOLD, 12));
        loadData();
    }

    public void loadData() {
        listTest = (ArrayList<Test>) testDAO.getAllTest();
        jTableTest.setModel(new CustomTableTest(listTest));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelTableMain = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableQuestions = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonAddTest = new javax.swing.JButton();
        jButtonChangeStatus = new javax.swing.JButton();

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(4, 178, 217));

        jLabelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))); // NOI18N
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBackMousePressed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("QUẢN LÝ ĐỀ THI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318)
                .addComponent(jLabelTitle)
                .addGap(0, 406, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBack, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, -1));

        jPanelTableMain.setBackground(new java.awt.Color(4, 135, 217));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableTest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTest.setFocusable(false);
        jTableTest.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableTest.setOpaque(false);
        jTableTest.setRowHeight(22);
        jTableTest.setShowVerticalLines(false);
        jTableTest.getTableHeader().setReorderingAllowed(false);
        jTableTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTestMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableTestMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTest);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Danh sách đề thi");

        jTableQuestions.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableQuestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableQuestions.setEnabled(false);
        jTableQuestions.setFocusable(false);
        jTableQuestions.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableQuestions.setOpaque(false);
        jTableQuestions.setRowHeight(22);
        jTableQuestions.setShowVerticalLines(false);
        jTableQuestions.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableQuestions);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Danh sách câu hỏi theo đề");

        jButtonAddTest.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddTest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddTest.setForeground(new java.awt.Color(4, 135, 217));
        jButtonAddTest.setText("THÊM ĐỀ THI");
        jButtonAddTest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTestActionPerformed(evt);
            }
        });

        jButtonChangeStatus.setBackground(new java.awt.Color(255, 255, 255));
        jButtonChangeStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonChangeStatus.setForeground(new java.awt.Color(4, 135, 217));
        jButtonChangeStatus.setText("ĐỔI TRẠNG THÁI");
        jButtonChangeStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonChangeStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTableMainLayout = new javax.swing.GroupLayout(jPanelTableMain);
        jPanelTableMain.setLayout(jPanelTableMainLayout);
        jPanelTableMainLayout.setHorizontalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTableMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTableMainLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddTest, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanelTableMainLayout.setVerticalGroup(
            jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTableMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelTableMainLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableMainLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(27, 27, 27)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
            .addGroup(jPanelTableMainLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButtonAddTest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanelTableMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1130, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        // TODO add your handling code here:
        jLabelBack.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon_hover.png"))));
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        // TODO add your handling code here:
        jLabelBack.setIcon((new javax.swing.ImageIcon(getClass().getResource("/Image/backicon.png"))));
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jLabelBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMousePressed
        // TODO add your handling code here:
        JPanel a = (JPanel) this.getParent();
        a.removeAll();
        a.add(new MainAdminPanel());
        a.revalidate();
    }//GEN-LAST:event_jLabelBackMousePressed

    private void jTableTestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTestMousePressed
        // TODO add your handling code here:
        int indexTest = jTableTest.getSelectedRow();
        try {
            if (indexTest >= 0) {
                int Test_ID = listTest.get(indexTest).getTest_ID();
                loadListQuestionByTest(Test_ID);
                if (((String) jTableTest.getValueAt(indexTest, 3)).compareToIgnoreCase("Hoạt động") == 0) {
                    jButtonChangeStatus.setText("Vô hiệu hóa");
                } else {
                    jButtonChangeStatus.setText("Kích hoạt");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTableTestMousePressed

    private void jButtonChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeStatusActionPerformed
        // TODO add your handling code here:
        changeTestStatus();
    }//GEN-LAST:event_jButtonChangeStatusActionPerformed

    private void jButtonAddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTestActionPerformed
        // TODO add your handling code here:
        AddAndEditTestForm f = new AddAndEditTestForm(null, true, this);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButtonAddTestActionPerformed

    private void jTableTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTestMouseClicked
        // TODO add your handling code here:
            int indexTest = jTableTest.getSelectedRow();
        if (evt.getClickCount() == 2) {     // to detect doble click events
            AddAndEditTestForm f = new AddAndEditTestForm(null, true, listTest.get(indexTest));
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            loadData();
        }
    }//GEN-LAST:event_jTableTestMouseClicked

    private void loadListQuestionByTest(int Test_ID) {
        listQuestion = (ArrayList<Question>) questionDAO.getListQuestionByTestID(Test_ID);
        jTableQuestions.setModel(new CustomTableTestQuestion(listQuestion));
    }
    
    private void changeTestStatus() {
        try {
            int indexTest = jTableTest.getSelectedRow();

            if (indexTest >= 0) {
                int Test_ID = listTest.get(indexTest).getTest_ID();

                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn "+jButtonChangeStatus.getText()
                        +" mã đề " + listTest.get(indexTest).getTest_Name(),
                        "Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if (testDAO.changeTestStatusByID(Test_ID)) {
                        loadData();
                        throw new Exception(jButtonChangeStatus.getText()+" thành công!!!");
                    } else {
                        throw new Exception(jButtonChangeStatus.getText()+" không thành công!!!");
                    }
                }
            } else {
                throw new Exception("Chưa chọn đề!!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTest;
    private javax.swing.JButton jButtonChangeStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTableMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableQuestions;
    private javax.swing.JTable jTableTest;
    // End of variables declaration//GEN-END:variables
}
